version: '3'

services:
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://user:user@db:5432/contacts_base
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=contacts_base
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql